---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[test]
      - recipe[chef-server-populator]
    attributes:
      chef-server:
        version: 12.0.5-1
      chef_server_populator:
        endpoint: localhost
        solo_org:
          validator_pub_key: validator_pub.pem
        org_users:
          pub_key: user_pub.pem
        clients:
          test-node: client_key_pub.pem
